/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-06-04 03:17:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ppc.Ticket_sell.bean.WorkerBean;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>汽车售票系统</title>\r\n");
      out.write("<script src=\"js/jquery-1.8.0.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-easyui-1.3.5/jquery.easyui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"js/jquery-easyui-1.3.5/themes/default/easyui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"js/jquery-easyui-1.3.5/themes/icon.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/main.js?time=\"></script>\r\n");
      out.write("</head>\r\n");
   
     Integer jd=0;
     if(request.getSession().getAttribute("worker") == null) { 
    			response.sendRedirect("clearSession.jsp");
     }else{
       WorkerBean worker=(WorkerBean)request.getSession().getAttribute("worker");
       if(worker.getJurisdiction()!=null &&  worker.getJurisdiction().getJurisdictionNum()!=null){
    	 jd=worker.getJurisdiction().getJurisdictionNum();
        }
     }

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<body class=\"easyui-layout\" style=\"width:100%;margin: auto\" > \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.history.go(1);\r\n");
      out.write("</script>   \r\n");
      out.write("    <div region=\"north\" href=\"top.jsp\" style=\"height:100px;overflow-y: hidden\" ></div>    \r\n");
      out.write("    <div data-options=\"region:'west',title:'导航',split:false\" style=\"width:200px;\">\r\n");
      out.write("      <div class=\"easyui-accordion\" fit=\"true\" border=\"false\">\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\t\t<div title=\"售票管理\" selected=\"false\">\r\n");
      out.write("\t\t\t<ul >\r\n");
      out.write("\t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-redo\" onclick=\"navigation('售票管理', 'ticketSell.jsp','");
      out.print(jd);
      out.write("')\">售票管理</a></li>\r\n");
      out.write("\t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-redo\" onclick=\"navigation('取票管理', 'ticketGet.jsp','");
      out.print(jd);
      out.write("')\">取票管理</a></li>\r\n");
      out.write("\t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\"  iconCls=\"icon-redo\" onclick=\"navigation('退票管理', 'ticketReturn.jsp','");
      out.print(jd);
      out.write("')\">退票管理</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"车票管理\" >\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-redo\" onclick=\"navigation('车票管理', 'ticketManage.jsp','");
      out.print(jd);
      out.write("')\">车票管理</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div title=\"职工管理\" selected=\"false\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\" class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-redo\"onclick=\"navigation('职工管理', 'workerManage.jsp','");
      out.print(jd);
      out.write("')\">职工管理</a></li>\r\n");
      out.write("<!-- \t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\"  class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-redo\" onclick=\"navigation('权限管理', 'jdManage.jsp')\">权限管理</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t<li style=\"list-style-type:none;\"><a href=\"#\"  class=\"easyui-linkbutton\" plain=\"true\" iconCls=\"icon-redo\" onclick=\"navigation('职位管理', 'jobManage.jsp')\">职位管理</a></li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("     \r\n");
      out.write("    </div>    \r\n");
      out.write("    <div  id=\"center_region\" data-options=\"region:'center'\" title=\"欢迎\" style=\"padding:0px;overflow: hidden;\">\r\n");
      out.write("      <iframe id=\"center_iframe\" src=\"welcome.jsp\" style=\"height: 100%; width: 100%; \" scrolling=\"no\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("</body>    \r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
