/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-06-04 03:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ticketSell_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"js/jquery-1.8.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.PrintArea.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/print.css\" type=\"text/css\" media=\"print\"/>\r\n");
      out.write("<script src=\"js/jquery-easyui-1.3.5/jquery.easyui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"js/jquery-easyui-1.3.5/themes/default/easyui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"js/jquery-easyui-1.3.5/themes/icon.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ticketSell.js?time=\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>售票界面</title>\r\n");

    if(request.getSession().getAttribute("worker") == null) {
		response.sendRedirect("clearSession.jsp");
    }

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <input id=\"workerName\" type=\"hidden\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.worker.workerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'/>\r\n");
      out.write(" <input id=\"name\" type=\"hidden\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.worker.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'/>\r\n");
      out.write("  <div id=\"ticketSellDg\"></div>\r\n");
      out.write("  <div id=\"ticketSellTb\">\r\n");
      out.write("   <br>\r\n");
      out.write("    <table>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>&nbsp;起点站：<input type=\"text\" id=\"start_stationQuery\" style=\"width:80px\" value=''/></td>\r\n");
      out.write("        <td>&nbsp;终点站：<input type=\"text\" id=\"end_stationQuery\" style=\"width:80px\" value=''/>&nbsp;</td>\r\n");
      out.write("        <td>日期：<input id=\"dateQuery\" class=\"easyui-datebox\"  style=\"width:100px\"></input>&nbsp;</td>\r\n");
      out.write("        <td><a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"doSearch()\">查询</a></td>\r\n");
      out.write("      <tr>\r\n");
      out.write("    </table>\r\n");
      out.write("  </div> \r\n");
      out.write("  <div id=\"orderInfo\" icon=\"icon-save\"\r\n");
      out.write("\tstyle=\"padding: 5px; width: 500px; height: 300px;\">\r\n");
      out.write("\t<div  class=\"printDiv\" style=\"width:450px ;height:210px;margin: auto\" id=\"orderInfo_table\" >\t\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"1px\" style=\"margin: auto\" cellpadding=\"0\" cellspacing=\"0\" >\r\n");
      out.write("\t  <tr><td width=\"20%\"><label>订单编号：</label></td><td width=\"30%\"><label id=\"orderInfo_orderNum\"></label></td><td width=\"20%\"><label>价格：</label></td><td width=\"30%\"><label id=\"orderInfo_price\"></label></td></tr>\r\n");
      out.write("\t  <tr><td ><label>起点站：</label></td><td><label id=\"orderInfo_start_station\"></label></td><td ><label>终点站：</label></td><td ><label id=\"orderInfo_end_station\"></label></td></tr>\r\n");
      out.write("\t  <tr><td ><label>乘车日期：</label></td><td ><label id=\"orderInfo_date\"></label></td><td ><label>出发时间：</label></td><td ><label id=\"orderInfo_time\"></label></td></tr>\r\n");
      out.write("\t  <tr><td ><label>汽车编号：</label></td><td ><label id=\"orderInfo_moNum\"></label></td><td ><label>座位号：</label></td><td ><label id=\"orderInfo_seatNo\"></label></td></tr>\r\n");
      out.write("\t  <tr><td ><label>乘客：</label></td><td ><label id=\"orderInfo_passengerName\"></label></td><td ><label>操作员：</label></td><td ><label id=\"orderInfo_worker_name\"></label></td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table style=\"margin: auto\">\r\n");
      out.write("\t   <tr><td><a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-print\" onclick=\"printOrder()\">打印</a></td><td><a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-cancel\" onclick=\"closeDialog_orderInfo()\">取消</a></td></tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("  </div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
