/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-06-04 04:34:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class workerManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>职工管理</title>\r\n");
      out.write("<script src=\"js/jquery-1.8.0.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-easyui-1.3.5/jquery.easyui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"js/jquery-easyui-1.3.5/themes/default/easyui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"js/jquery-easyui-1.3.5/themes/icon.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/wokerManage.js?time=\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

    if(request.getSession().getAttribute("worker") == null) {
		response.sendRedirect("clearSession.jsp");
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- toolbar -->\r\n");
      out.write(" <div id=\"workerTb\">\r\n");
      out.write("  <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\" onclick=\"openDialog_add()\">添加</a>\r\n");
      out.write("  <a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\" onclick=\"DeleteS()\">删除</a>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div>\r\n");
      out.write("   <table>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td>&nbsp;登录账号：<input type=\"text\" id=\"workerNameQuery\" style=\"width:80px\" value='' />\r\n");
      out.write("          &nbsp;职工姓名：<input type=\"text\" id=\"nameQuery\" style=\"width:80px\" value=''/>&nbsp;</td>\r\n");
      out.write("      <td><a href=\"#\" iconCls=\"icon-search\" class=\"easyui-linkbutton\" onclick=\"doSearch()\">查询</a></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <!-- datagrid -->\r\n");
      out.write("  <div id=\"workerDg\"></div>\r\n");
      out.write("  \r\n");
      out.write("    <!--编辑-->\r\n");
      out.write("  <div id=\"workerEdit\" icon=\"icon-save\"\r\n");
      out.write("\tstyle=\"padding: 5px; width: 500px; height: 300px;\">\r\n");
      out.write("\t<h5 id=\"workerEdit_message\" style=\"color: red;\"></h5>\r\n");
      out.write("\t<div class=\"ToolTip_Form\" id=\"table_workerEdit\"  onkeydown=\"if(event.keyCode==13){workerEdit();}\">\r\n");
      out.write("\t  <div style=\"height: 100%;width: 100%;margin:auto\">\r\n");
      out.write("\t   <table  border=\"0px\" cellspacing=\"0\" style=\"margin: auto\" >\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>登录账号：</label></td><td><input  type=\"text\"  id=\"workerEdit_workerName\" maxlength=\"8\" readonly=\"readonly\"></td><td></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>密码：</label></td><td><input type=\"text\"  id=\"workerEdit_password\" maxlength=\"8\" ></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>职工姓名：</label></td><td><input type=\"text\"  id=\"workerEdit_name\" maxlength=\"8\" ></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>职工电话：</label></td><td><input type=\"text\"  id=\"workerEdit_tel\" maxlength=\"11\" ></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>职位：</label></td><td><select id=\"jobCcEdit\" style=\"width:100px\"></select></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>权限：</label></td><td><select id=\"jdCcEdit\" style=\"width:100px\"></select></td></tr>\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t   <table style=\"margin: auto\">\r\n");
      out.write("\t   <tr><td style=\"width: 50%\"><a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-ok\" onclick=\"workerEdit();\">提交</a></td><td><a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-redo\" onclick=\"closeDialog_edit()\">取消</a></td></tr>\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t  </div>\r\n");
      out.write("<!--         <ul> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>登录账号：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\"  id=\"workerEdit_workerName\" maxlength=\"8\" readonly=\"readonly\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>密码：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerEdit_password\" maxlength=\"10\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>职工姓名：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerEdit_name\" maxlength=\"20\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>职工电话：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerEdit_tel\" maxlength=\"20\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>职位：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<select id=\"jobCcEdit\" style=\"width:100px\"></select> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>权限：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<select id=\"jdCcEdit\" style=\"width:100px\"></select> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-ok\" onclick=\"workerEdit();\">提交</a> -->\r\n");
      out.write("<!-- \t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-redo\" onclick=\"workerEditReset();\">重置</a> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t</ul> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("  <!-- 添加 -->\r\n");
      out.write("  <div id=\"workerAdd\" icon=\"icon-save\"\r\n");
      out.write("\tstyle=\"padding: 5px; width: 500px; height: 300px;\">\r\n");
      out.write("\t<h5 id=\"workerAdd_message\" style=\"color: red;\"></h5>\r\n");
      out.write("\t<div class=\"ToolTip_Form\" id=\"table_workerAdd\" onkeydown=\"if(event.keyCode==13){workerAdd();}\">\r\n");
      out.write("\t   <div style=\"height: 100%;width: 100%;margin:auto\">\r\n");
      out.write("\t   <table  border=\"0px\" cellspacing=\"0\" style=\"margin: auto\" >\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>登录账号：</label></td><td><input  type=\"text\"  id=\"workerAdd_workerName\" maxlength=\"8\" ></td><td></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>密码：</label></td><td><input type=\"text\"  id=\"workerAdd_password\" maxlength=\"8\" ></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>职工姓名：</label></td><td><input type=\"text\"  id=\"workerAdd_name\" maxlength=\"8\" ></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>职工电话：</label></td><td><input type=\"text\"  id=\"workerAdd_tel\" maxlength=\"11\" ></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>职位：</label></td><td><select id=\"jobCcAdd\" style=\"width:100px\"></select></td></tr>\r\n");
      out.write("\t     <tr><td style=\"width: 30%\"><label>权限：</label></td><td><select id=\"jdCcAdd\" style=\"width:100px\"></select></td></tr>\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t   <table style=\"margin: auto\">\r\n");
      out.write("\t   <tr><td style=\"width: 50%\"><a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-ok\" onclick=\"workerAdd();\">提交</a></td><td><a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-redo\" onclick=\"workerAddReset();\">重置</a></td></tr>\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t  </div>\r\n");
      out.write("<!--         <ul> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>登录账号：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerAdd_workerName\" maxlength=\"8\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>密码：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerAdd_password\" maxlength=\"10\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>职工姓名：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerAdd_name\" maxlength=\"20\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>职工电话：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<input type=\"text\" class=\"easyui-validatebox\" id=\"workerAdd_tel\" maxlength=\"20\" required=\"true\"></input> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>职位：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<select id=\"jobCcAdd\" style=\"width:100px\"></select> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<label>权限：</label> -->\r\n");
      out.write("<!-- \t\t\t\t<select id=\"jdCcAdd\" style=\"width:100px\"></select> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t\t<li> -->\r\n");
      out.write("<!-- \t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-ok\" onclick=\"workerAdd();\">提交</a> -->\r\n");
      out.write("<!-- \t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" icon=\"icon-redo\" onclick=\"workerAddReset();\">重置</a> -->\r\n");
      out.write("<!-- \t\t\t</li> -->\r\n");
      out.write("<!-- \t\t</ul> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
